apiVersion: v1
kind: Service
metadata:
  name: react-node-cms
  namespace: react-node-cms
spec:
  type: ClusterIP
  selector:
    app: react-node-cms
  ports:
    - port: 80
      targetPort: 3008
      protocol: TCP
